# Generated by Django 3.1.5 on 2021-01-08 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210108_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 8, 2, 17, 604420), verbose_name='date published'),
        ),
    ]
