# Generated by Django 3.1.5 on 2021-01-08 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210108_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 8, 6, 26, 22118), verbose_name='date published'),
        ),
    ]
